### PR TITLE
Upgrade mongodb driver to 2.0

### PR DESCRIPTION
**Pull request by ambrosechua**
Upgrade mongodb driver, enabling support for recent mongod versions

### CODE REVIEW

**Comment by ambrosechua** [comment]
Build error has something to do with the build environment. Even master is failing

**Comment by ambrosechua** [comment]
Sorry 'bout the long chain of commits :smile:

**Comment by gpapin** [comment]
Any update on this ? I need it to fix #63

**Comment by ambrosechua** [comment]
See #71

**Comment by soupman99** [comment]
How the hell do I update this thing?

**Comment by ambrosechua** [comment]
see #76

**Pull request closed without merging**
